### @name createProfile
POST http://localhost:3001/profile
Content-Type: application/json

{
  "userId": "user-123",
  "firstName": "Jane",
  "lastName": "Doe",
  "maritalStatus": "single",
  "education": ["MIT", "Harvard"],
  "workExperience": [
    {
      "position": "Backend Developer",
      "company": "Tech Inc",
      "years": "2019–2023"
    }
  ],
  "techStack": {
    "languages": ["TypeScript", "Go"],
    "frameworks": ["Fastify", "Express"],
    "tools": ["Docker", "Git"]
  },
  "spokenLanguages": ["English", "Spanish"],
  "yearsOfExperience": 5,
  "softSkills": ["problem-solving", "communication"],
  "avatarUrl": "https://example.com/avatar.jpg"
}

### @name getProfile
GET http://localhost:3001/profile/

### @name deleteProfile
DELETE http://localhost:3001/profile/

### @name createToken
POST http://localhost:3001/token
Content-Type: application/json

{
  "profileId": "",
  "expiresIn": 3600,
  "isOneTime": true
}